# Generated by Django 5.1.7 on 2025-04-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorprofile",
            name="recommendations",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
