# Generated by Django 5.1.7 on 2025-04-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_job_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="title",
        ),
    ]
