# Generated by Django 5.1.7 on 2025-04-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorprofile",
            name="onboarding_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="onboarding_step",
            field=models.IntegerField(default=0),
        ),
    ]
